server:
  port: 8888

logging:
  path: logs
  file: userManager.log

spring:
  application:
    name: userManeger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?serverTimezone=GMT
    username: root
    password: 123456

mybatis:
  type-aliases-packet: com.course.model
  mapper-locations:
    - mapper/*
