server:
  port: 8888

logging:
  path: log
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: 123456

mybatis:
  type-aliases-packet: com.course.model
  mapper-locations:
    - mapper/*

